include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - "**/*.g.dart"
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

formatter:
  page_width: 120

linter:
  rules:
    prefer_single_quotes: true
    unawaited_futures: true
