targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: false
          named_parameters: true
          sql:
            dialect: sqlite
            options:
              version: "3.45"
              modules: [math]
